import "stdlib.k";

# class Test{
#     test = 1;
#     init(a, otherObj){
#         this.a = a;
#         this.obj = otherObj;
#     }
#     getA(){
#         return this.obj.LOL;
#     }
# }

# class Useless {
#     LOL = 69;
# }


# var x = 2;
# var x = [0, 3];

var s = List();


# print x;

# (if (true){});
# print Test(1, Useless).getA();

# var da =  LOLXD();
# da._t();
# print "b4 edit: "+Test.t;
# print "b4 editr: "+t.t;
# Test.t = "assda";
# print "after class edit:" + Test.t;
# print "after class edit:" + t.t;
# t.t = "-1";
# print "after instance edit: t.t=" + t.t;
# print "after instance edit: Test.t=" +Test.t;
